name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - run: npm i
      - run: npm install json -g
      - run: json -I -f package.json -e 'this.homepage="https://aicacia.gitlab.io/expo-fishbowl/"'
      - run: json -I -f web/manifest.json -e 'this.start_url="/expo-fishbowl/?utm_source=web_app_manifest"'
      - run: npm run build.web
      - run: cp web/404.html web-build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
